<?php
/** @var \ConferenceTools\Attendance\Domain\Sponsor\ReadModel\Sponsor $sponsor */
$sponsor = $this->sponsor;
/** @var \ConferenceTools\Attendance\Domain\DataSharing\ReadModel\DelegateList $delegateList */
$delegateList = $this->delegateList;
?>
<div class="row">
    <div class="col-md-12">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Welcome to the sponsors dashboard</div>
            </div>
            <div class="card-body ">
                <p>
                    This is the sponsorship dashboard which provides two important features to enable you to get the most out of your sponsorship, our data sharing application and out prize draw application.
                </p>

                <p>
                    If you have any prizes to give away, set them up below. There are three types of prize draw:
                </p>
                <dd>
                    <dt>Random draw</dt><dl>This draw type will automatically pick a winner from all the delegates who are in attendance of the event</dl>
                    <dt>From list</dt><dl>This will pick a random delegate who has visited you at the event and you've scanned their badge (see below)</dl>
                    <dt>Prechosen winner</dt><dl>This allows you to name the winner, for example if you're running a competition of some form</dl>
                </dd>
                <p>
                    We will then be able to announce the winners during the closing keynote. In the event that the delegate is unable to collect their prize at the event, their details
                    will be supplied to you so you can contact them yourselves and arrange for the delivery of their prize. Please ensure any chosen winner prizes are entered prior to
                    the start of the closing keynote.
                </p>
                <p>
                    Our data sharing platform has been designed to allow you to generate leeds from delegates interested in your company and also comply with your obligations to protect
                    personal information under the GDPR. It requires a little bit of setup on your side to work effectively. Below you have the option to add one or more data usage purposes
                    which delegates can then opt into. After the event, delegates will be given the chance to review their choices before we make the list available for you to download. Only
                    delegates who consent to at least one purpose will be included on your list.
                </p>
                <p>
                    Once you have completed setup, you will get a link to be able to add delegates to your list; this is done by scanning the QR code on the delegates badge, doing so will then
                    pop up an opt in form. You should hand the device to the delegate to allow them to opt into the purposes which they are interested in and submit the form. Submitting the form
                    will automatically enter them into any prize draws you've created with the type of <b>From list</b> unless they explicitly opt out, they will be able to enter the prize draw
                    regardless of their choices to opt in to further communication from you.
                </p>
            </div>
        </div>
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Data sharing questions</div>
            </div>
            <div class="card-body ">
                <?php if (count($this->sponsor->getQuestions()) === 0):?>
                    <p>Please define your questions below</p>
                <?php else:?>
                    <table class="table table-hover table-in-card">
                        <thead>
                        <tr>
                            <th scope="col">Handle</th>
                            <th scope="col">Question</th>
                            <th scope="col">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->sponsor->getQuestions() as $optIn):
                            /** @var \ConferenceTools\Attendance\Domain\DataSharing\OptIn $optIn */
                            ?>
                            <tr>
                                <td><?=$this->escapeHtml($optIn->getHandle())?></td>
                                <td><?= $this->escapeHtml($optIn->getQuestion())?></td>
                                <td>
                                    <?php if ($this->sponsor->getDelegateListId() === null):?>
                                        <a class="btn btn-danger" href="<?=$this->url('attendance-sponsor/questions/delete', ['handle' => $optIn->getHandle()])?>">Delete</a>
                                    <?php endif;?>
                                </td>
                            </tr>
                        <?php
                        endforeach;?>
                        </tbody>
                    </table>
                <?php endif;?>
                <?php if ($this->sponsor->getDelegateListId() === null):?>
                    <a class="btn btn-success mt-3" href="<?=$this->url('attendance-sponsor/questions/add')?>">Add question</a>
                    <p class="mt-3">Once you have added all the questions click this button. Once you have confirmed this, you will not be able to edit the questions above</p>
                    <a class="btn btn-success mt-3" href="<?=$this->url('attendance-sponsor/delegatelist/create')?>">Complete setup</a>
                <?php else: ?>
                    <?php if ($delegateList->isListTerminated()): ?>
                        <?php if ($delegateList->isListAvailable()):?>
                            <a class="btn btn-success mt-3" href="<?=$this->url('attendance-sponsor/delegatelist/scan')?>">Download list</a>
                        <?php else: ?>
                            <?php
                                if ($delegateList->getAvailableTime() === null) {
                                    $availableAt = 'soon';
                                } else {
                                    $availableAt = $delegateList->getAvailableTime()->format('on Y-m-d \a\t H:i');
                                }
                            ?>

                            <p>Your list will be available to download <?=$availableAt?></p>
                        <?php endif ?>
                    <?php else: ?>
                        <a class="btn btn-success mt-3" href="<?=$this->url('attendance-sponsor/delegatelist/scan')?>">Add delegates to list</a>
                        <?php if ($delegateList->getLastCollectionTime() !== null):?>
                            <p class="mt-3">You will be able to add delegates to your list until <?=$delegateList->getLastCollectionTime()->format('Y-m-d \a\t H:i');?></p>
                        <?php endif?>
                    <?php endif?>
                <?php endif ?>
            </div>
        </div>
    </div>
</div>