<div class="row" >
    <div class="col-md-8">
        <form method="get" action="<?=$this->url('attendance-admin/purchase/delegates')?>">
            <div class="panel panel-default credit-card-box">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        Create Purchase
                    </h4>
                </div>
                <div class="panel-body">
                    <div style="padding: 15px;">
                        <?=$this->form($this->form)?>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
