<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-default credit-card-box">
            <div class="panel-heading display-table" >
                <div class="row display-tr" >
                    <h3 class="panel-title display-td" >Reports</h3>
                </div>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-xs-12">
                        <a href="<?=$this->url('attendance-admin/reports/catering/preferences')?>" >Catering Preferences</a>
                        <a href="<?=$this->url('attendance-admin/reports/catering/allergies')?>" >Catering Allergies</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>