<div class="row">
    <div class="col-md-12">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title"><?=$this->title?></div>
                <a class="btn btn-primary ml-5" href="?download=true">Download</a>
            </div>
            <div class="card-body ">
                <?php if (count($this->report) === 0):?>
                    The report returned no results
                <?php else:?>
                <table class="table table-hover table-in-card">


                    <?php if (isset($this->header)):?>
                        <tr>
                            <?php foreach ($this->header as $heading): ?>
                                <th><?=$heading?></th>
                            <?php endforeach;?>
                        </tr>
                    <?php endif;?>


                    <?php foreach ($this->report as $row):
                        ?>
                        <tr>
                            <?php foreach ($row as $column):?>
                                <td><?=$this->escapeHtml($column)?></td>
                            <?php endforeach;?>
                        </tr>
                    <?php
                    endforeach;
                endif;
                ?>
            </table>
            </div>
        </div>
    </div>
</div>