
<div id="qr" style="display:none" class="panel panel-default">
    <div class="panel-heading display-table credit-card-box">
        <div class="row display-tr">
            <h3 class="panel-title display-td">Scan QR code</h3>
            <div class="display-td"></div>
        </div>
    </div>
    <div class="panel-body" style="padding: 30px">
        <button id="scan-again" class="btn btn-info">Scan again</button>
        <video id="preview" style="display:none; margin:auto; width: 100%"></video>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading display-table credit-card-box" >
        <div class="row display-tr" >
            <h3 class="panel-title display-td" >Search</h3>
            <div class="display-td" ></div>
        </div>
    </div>
    <div class="panel-body" style="padding: 30px">
        <?php echo $this->form($this->form);?>
    </div>
</div>
<div class="panel panel-default credit-card-box">
    <div class="panel-heading display-table" >
        <div class="row display-tr" >
            <h3 class="panel-title display-td" >Results</h3>
            <div class="display-td" ></div>
        </div>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-hover">

            <thead>
            <tr>
                <th>Name</th>
                <th>Tickets</th>
                <th>Delegate Email</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
                <?php foreach ($this->results as $delegate):?>
                    <?php /** @var \ConferenceTools\Attendance\Domain\Delegate\ReadModel\Delegate $delegate */?>
                    <tr>
                        <td><?=$this->escapeHtml($delegate->getName())?></td>
                        <td>
                            <?php
                            $displayTickets = [];
                            foreach ($delegate->getTickets() as $ticket) {
                                $displayTickets[] = $this->tickets[$ticket]->getEvent()->getName();
                            }
                            echo implode(', ', $displayTickets);
                            ?>

                        </td>
                        <td>
                            <?=$this->escapeHtml($delegate->getEmail())?>
                            <?php if ($delegate->getEmail() !== $delegate->getPurchaserEmail()): ?>
                            , <?=$this->escapeHtml($delegate->getPurchaserEmail())?>
                            <?php endif?>
                        </td>
                        <td>
                            <?php if ($delegate->checkedIn()):?>
                                Checked In
                            <?php else:?>
                                <a href="<?=$this->url('attendance-admin/checkin/checkin', ['delegateId' => $delegate->getId()])?>">Check in</a>
                            <?php endif?>
                        </td>
                    </tr>
                <?php endforeach;?>

            </tbody>

        </table>
    </div>
</div>
<script type="module">
    import QrScanner from "/js/qr-scanner.min.js";
    QrScanner.WORKER_PATH = '/js/qr-scanner-worker.min.js';
    QrScanner.hasCamera().then(hasCamera => {
        if (hasCamera) {
            $('#qr').show()
        }
    });
    const video = document.getElementById('preview');
    const scanner = new QrScanner(video, result => setResult(result));

    function setResult(result) {
        if (result.length > 0) {
            $('input[name="id"]').val(result);
            $('#qr').hide();
            $('button[name="submit"]').click();
            scanner.stop();
        }
    }
    function startScanning() {
        $('#preview').show();
        $('#scan-again').hide();
        scanner.start();
    }

    $('#scan-again').bind('click', startScanning);

    <?php if (!$this->hasScanned):?>
        startScanning();
    <?endif;?>

</script>