
<div id="qr" style="display:none" class="panel panel-default">
    <div class="panel-heading display-table credit-card-box">
        <div class="row display-tr">
            <h3 class="panel-title display-td">Scan QR code</h3>
            <div class="display-td"></div>
        </div>
    </div>
    <div class="panel-body" style="padding: 30px">
        <button id="scan-again" class="btn btn-info">Scan again</button>
        <video id="preview" style="display:none; margin:auto; width: 100%"></video>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Search</div>
            </div>
            <div class="card-body ">
        <?php echo $this->form($this->form);?>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Results</div>
            </div>
            <div class="card-body ">
                <?php if (count($this->results) === 0):?>
                    No delegates were found in the search.
                <?php else:?>
                <table class="table table-hover table-in-card">

            <thead>
            <tr>
                <th>Name</th>
                <th>Tickets</th>
                <th>Delegate Email</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
                <?php foreach ($this->results as $delegate):?>
                    <?php /** @var \ConferenceTools\Attendance\Domain\Delegate\ReadModel\Delegate $delegate */?>
                    <tr>
                        <td><?=$this->escapeHtml($delegate->getName())?></td>
                        <td>
                            <?php
                            $displayTickets = [];
                            foreach ($delegate->getTickets() as $ticket) {
                                $displayTickets[] = $this->tickets[$ticket]->getDescriptor()->getName();
                            }
                            echo implode(', ', $displayTickets);
                            ?>

                        </td>
                        <td>
                            <?=$this->escapeHtml($delegate->getEmail())?>
                        </td>
                        <td>
                            <?php if ($delegate->checkedIn()):?>
                                Checked In
                            <?php else:?>
                                <a href="<?=$this->url('attendance-admin/checkin/checkin', ['delegateId' => $delegate->getId()])?>">Check in</a>
                            <?php endif?>
                        </td>
                    </tr>
                <?php endforeach;?>

            </tbody>

        </table>
                <?php endif?>
    </div>
</div>
<script type="module">
    import QrScanner from "/js/qr-scanner.min.js";
    QrScanner.WORKER_PATH = '/js/qr-scanner-worker.min.js';
    QrScanner.hasCamera().then(hasCamera => {
        if (hasCamera) {
            $('#qr').show()
        }
    });
    const video = document.getElementById('preview');
    const scanner = new QrScanner(video, result => setResult(result));

    function setResult(result) {
        if (result.length > 0) {
            $('input[name="checkinId"]').val(result);
            $('#qr').hide();
            $('button[name="submit"]').click();
            scanner.stop();
        }
    }
    function startScanning() {
        $('#preview').show();
        $('#scan-again').hide();
        scanner.start();
    }

    $('#scan-again').bind('click', startScanning);

    <?php if (!$this->hasScanned):?>
        startScanning();
    <?endif;?>

</script>