<?php

$this->headLink()->appendStylesheet('/css/card.css');
?>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default credit-card-box">
            <div class="panel-heading display-table" >
                <div class="row display-tr" >
                    <h3 class="panel-title display-td" >Purchase Completed</h3>
                    <div class="display-td" ></div>
                </div>
            </div>
            <div class="panel-body">
                <?php foreach ($this->purchase->getTickets() as $ticketId => $quantity): ?>
                    <div class="row">
                        <span class="col-xs-12 col-md-8"><?= $this->tickets[$ticketId]->getTicket()->getName() ?></span>
                        <span class="col-xs-12 col-md-4"><?= $quantity ?></span>
                        <?php if ( ! empty($this->tickets[$ticketId]->getTicket()->getDescription())): ?>
                            <span class="help-block col-xs-12 col-md-12"><?= $this->tickets[$ticketId]->getTicket()->getDescription() ?></span>
                        <?php endif ?>
                    </div>
                <?php endforeach; ?>
                <hr />
                <div class="row">
                    <span class="col-xs-8"><strong>Sub Total</strong></span>
                    <span class="col-xs-4"><?= $this->moneyFormat($this->purchase->getTotal(), true) ?></span>
                </div>
                <div class="row">
                    <span class="col-xs-8"><strong>VAT</strong></span>
                    <span class="col-xs-4"><?= $this->moneyFormat($this->purchase->getTotal()->getTax()) ?></span>
                </div>
                <div class="row">
                    <span class="col-xs-8"><strong>Total</strong></span>
                    <span class="col-xs-4"><?= $this->moneyFormat($this->purchase->getTotal()) ?></span>
                </div>

            </div>
        </div>
    </div>
</div>

