<?php

$this->headLink()->appendStylesheet('/css/card.css');
?>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default credit-card-box">
            <div class="panel-heading display-table" >
                <div class="row display-tr" >
                    <h3 class="panel-title display-td" >Purchase Completed</h3>
                    <div class="display-td" ></div>
                </div>
            </div>
            <div class="panel-body">
                <?php foreach ($this->purchase->getTickets() as $ticketId => $quantity): ?>
                    <div class="row">
                        <span class="col-xs-12 col-md-8"><?= $this->tickets[$ticketId]->getDescriptor()->getName() ?></span>
                        <span class="col-xs-12 col-md-4"><?= $quantity ?></span>
                        <?php if ( ! empty($this->tickets[$ticketId]->getDescriptor()->getDescription())): ?>
                            <span class="help-block col-xs-12 col-md-12"><?= $this->tickets[$ticketId]->getDescriptor()->getDescription() ?></span>
                        <?php endif ?>
                    </div>
                <?php endforeach; ?>
                <?php foreach ($this->purchase->getMerchandise() as $merchandiseId => $quantity): ?>
                    <div class="row">
                        <span class="col-xs-12 col-md-8"><?= $this->merchandise[$merchandiseId]->getDescriptor()->getName() ?></span>
                        <span class="col-xs-12 col-md-4"><?= $quantity ?></span>
                        <?php if ( ! empty($this->merchandise[$merchandiseId]->getDescriptor()->getDescription())): ?>
                            <span class="help-block col-xs-12 col-md-12"><?= $this->merchandise[$merchandiseId]->getDescriptor()->getDescription() ?></span>
                        <?php endif ?>
                    </div>
                <?php endforeach; ?>
                <hr />
                <div class="row">
                    <span class="col-xs-8"><strong>Sub Total</strong></span>
                    <span class="col-xs-4"><?= $this->moneyFormat($this->purchase->getTotal(), true) ?></span>
                </div>
                <?php if ($this->discount):?>
                    <div class="row">
                        <span class="col-xs-8"><strong>Discount applied</strong></span>
                        <span class="col-xs-4"><?= $this->discount->getName() ?></span>
                    </div>
                <?php endif;?>
                <div class="row">
                    <span class="col-xs-8"><strong>VAT</strong></span>
                    <span class="col-xs-4"><?= $this->moneyFormat($this->purchase->getTotal()->getTax()) ?></span>
                </div>
                <div class="row">
                    <span class="col-xs-8"><strong>Total</strong></span>
                    <span class="col-xs-4"><?= $this->moneyFormat($this->purchase->getTotal()) ?></span>
                </div>

            </div>
        </div>
    </div>
</div>

<?php if (count($this->delegates) > 0):?>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default credit-card-box">
            <div class="panel-heading display-table" >
                <div class="row display-tr" >
                    <h3 class="panel-title display-td" >Delegates</h3>
                    <div class="display-td" ></div>
                </div>
            </div>
            <div class="panel-body">
                <?php foreach ($this->delegates as $delegate): ?>
                    <?php /** @var \ConferenceTools\Attendance\Domain\Delegate\ReadModel\Delegate $delegate */?>
                    <div class="row">
                        <?php
                        $tickets = $this->tickets;
                        $delegateTickets = array_map(function (string $ticketId) use ($tickets) {return $tickets[$ticketId]->getDescriptor()->getName();}, $delegate->getTickets());
                        ?>

                        <span class="col-xs-8">
                            <?= $delegate->getName()?>
                            <span class="help-block"><?= implode(', ', $delegateTickets) ?></span>
                        </span>
                        <span class="col-xs-4">
                            <a class="btn btn-primary" href="<?=$this->url('attendance/delegates', ['delegateId' => $delegate->getId()])?>">
                                Edit
                            </a>
                            <a class="btn btn-default" href="<?=$this->url('attendance/delegates/resend-ticket', ['delegateId' => $delegate->getId()])?>">
                                Resend Ticket Email
                            </a>
                        </span>


                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
<?php endif?>