<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-default credit-card-box">
            <div class="panel-heading display-table" >
                <div class="row display-tr" >
                    <h3 class="panel-title display-td" >Available tickets</h3>
                    <div class="display-td" ></div>
                </div>
            </div>
            <div class="panel-body">
                <form class="form-horizontal" method="POST" action="">
                    <div class="row">
                        <div class="col-xs-12">
                            <table class="table">
                                <?php if (count($this->tickets) === 0): ?>
                                    <tr>
                                        <td>Sorry, there are no tickets currently available</td>
                                    </tr>
                                <?php
                                else:
                                    foreach ($this->events['events'] as $event):
                                        ?>
                                    <tr>
                                        <td colspan="2">
                                            <?= $event->getDescriptor()->getName() ?>
                                            <?php if ( ! empty($event->getDescriptor()->getDescription())): ?>
                                                <span class="help-block"><?= $event->getDescriptor()->getDescription() ?></span>
                                            <?php endif ?>
                                            <?=$event->getStartsOn()->format('l \t\h\e jS \o\f F, Y h:i')?> until <?=$event->getEndsOn()->format('l \t\h\e jS \o\f F, Y h:i')?>
                                        </td>
                                    </tr>
                                    <?php foreach ($this->tickets as $id => $ticket):
                                        /** @var \ConferenceTools\Attendance\Domain\Ticketing\ReadModel\Ticket $ticket */
                                        ?>
                                        <?php if ($ticket->getRemaining() > 0 && $ticket->getEventId() === $event->getId()):?>
                                            <tr>
                                                <td class="col-md-9 col-xs-6">
                                                    <span style="margin-top:5px; margin-bottom: 10px;" class="col-xs-12 col-md-3"><?= $ticket->getDescriptor()->getName() ?></span>
                                                    <?php if ( ! empty($ticket->getDescriptor()->getDescription())): ?>
                                                        <span class="help-block col-xs-12 col-md-9"><?= $ticket->getDescriptor()->getDescription() ?></span>
                                                    <?php endif ?>
                                                </td>
                                                <td class="col-md-3 col-xs-6">
                                                    <span style="margin-top:5px; margin-bottom: 10px;" class="col-xs-6"><?= $this->moneyFormat($ticket->getPrice()) ?></span>
                                                    <span class="col-xs-6">
                                                        <?=$this->formInput($this->form->get('quantity')->get($ticket->getId()))?>
                                                        <span class="help-block"><?= $ticket->getRemaining() ?> remaining</span>
                                                    </span>
                                                </td>
                                            </tr>
                                        <?php endif; ?>
                                    <?php
                                    endforeach;
                                    endforeach;
                                endif;
                                ?>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="col-xs-offset-6 col-xs-6">
                                <?=$this->formRow($this->form->get('purchase_email'))?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="col-xs-offset-6 col-xs-6">
                                <?=$this->formRow($this->form->get('delegates'))?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="col-xs-offset-6 col-xs-6">
                                <?=$this->formRow($this->form->get('discount_code'))?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-12">
                                <div class="col-md-12">
                                    <div class="col-md-offset-11 col-md-1 col-xs-1 col-xs-offset-8">
                                        <button type="submit" class="btn btn-default">Continue</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>