
<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-default credit-card-box">
            <div class="panel-heading display-table" >
                <div class="row display-tr" >
                    <h3 class="panel-title display-td" >Please wait</h3>
                    <div class="display-td" ></div>
                </div>
            </div>
            <div class="panel-body">
                Your payment is being processed...
            </div>
        </div>
    </div>
</div>

<script>
    setTimeout(function () {window.location = window.location.href.split("#")[0];}, 5000);
</script>