<div class="row" >
    <div class="col-md-8">
        <form method="post">
            <div class="panel panel-default credit-card-box">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        Are you sure<?php if (!empty($this->action)):?> you want to <?=$this->action?><?php endif?>?
                    </h4>
                </div>
                <div class="panel-body">
                    <div style="padding: 15px;">
                        <?=$this->form($this->form)?>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
