<div class="row" >
    <div class="col-md-12">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-chart-bar"></i>
                </div>
                <div class="spur-card-title"> <?=$this->action?> </div>
            </div>
            <div class="card-body ">
                <?=$this->form($this->form)?>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        $('input[type="datetime"]').datetimepicker({"format": "YYYY-MM-DDThh:mmP", "sideBySide": true});
    });
</script>