<div class="row">
    <div class="col-md-12">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Tickets</div>
            </div>
            <div class="card-body ">
                <?php if (count($this->tickets) === 0):?>
                    You haven't created any tickets yet.
                <?php else:?>
                    <table class="table table-hover table-in-card">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Description</th>
                            <th scope="col">Quantity</th>
                            <th scope="col">Price</th>
                            <th scope="col">On sale from</th>
                            <th scope="col">Until</th>
                            <th scope="col">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->tickets as $id => $ticket):
                            /** @var \ConferenceTools\Attendance\Domain\Ticketing\ReadModel\Ticket $ticket */
                            ?>
                            <tr>
                                <td><?= $ticket->getDescriptor()->getName()?></td>
                                <td><?= $ticket->getDescriptor()->getDescription() ?></td>
                                <td><?= $ticket->getQuantity() ?></td>
                                <td><?= $this->moneyFormat($ticket->getPrice()) ?></td>
                                <td><?=($ticket->getOnSaleFrom() === null? 'N/A': $ticket->getOnSaleFrom()->format('Y-m-d h:i'))?></td>
                                <td><?=($ticket->getWithdrawFrom() === null? 'N/A': $ticket->getWithdrawFrom()->format('Y-m-d h:i'))?></td>
                                <td>
                                    <a class="btn btn-danger" href="<?=$this->url('attendance-admin/tickets/withdraw', ['ticketId' => $ticket->getId()])?>">
                                        Withdraw
                                    </a>
                                    <?php if (!$ticket->isOnSale()): ?>
                                        <a class="btn btn-warning" href="<?=$this->url('attendance-admin/tickets/put-on-sale', ['ticketId' => $ticket->getId()])?>">
                                            Put on Sale
                                        </a>
                                    <?php endif;?>
                                </td>
                            </tr>
                        <?php
                        endforeach;?>
                        </tbody>
                    </table>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>
