<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-default credit-card-box">
            <div class="panel-heading display-table" >
                <div class="row display-tr" >
                    <h3 class="panel-title display-td" >Tickets</h3>
                    <a class="btn btn-success" style="float:right" href="<?=$this->url('attendance-admin/tickets/new')?>">Add</a>
                </div>
            </div>
            <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-12">
                            <table class="table">
                                <?php if (count($this->tickets) === 0): ?>
                                    <tr>
                                        <td>You haven't created any tickets yet.</td>
                                    </tr>
                                <?php
                                else:
                                    foreach ($this->tickets as $id => $ticket):
                                        /** @var \ConferenceTools\Attendance\Domain\Ticketing\ReadModel\Ticket $ticket */
                                        ?>
                                        <tr>
                                            <td class="col-md-9 col-xs-6">
                                                <span class="col-xs-12 col-md-6"><?= $ticket->getEvent()->getName() ?></span>
                                                <span class="hidden-xs col-md-6">
                                                    <?= $ticket->getQuantity() ?>
                                                </span>
                                                <?php if ( ! empty($ticket->getEvent()->getDescription())): ?>
                                                    <span class="help-block col-xs-12 col-md-12"><?= $ticket->getTicket()->getDescription() ?></span>
                                                <?php endif ?>
                                            </td>
                                            <td class="col-md-3 col-xs-6">
                                                <span class="col-xs-6"><?= $this->moneyFormat($ticket->getPrice()) ?></span>
                                            </td>
                                        </tr>
                                    <?php
                                    endforeach;
                                endif;
                                ?>
                            </table>
                        </div>
                    </div>
            </div>
        </div>
    </div>
</div>