<?php $this->form->prepare();?>
<? $this->form($this->form)?>
<div class="row" >
    <div class="col-md-8">
        <form method="post">
            <div class="panel panel-default credit-card-box">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        Delegate Details
                    </h4>
                </div>
                <div class="panel-body">
                    <div style="padding: 15px;">
                        <?=$this->formCollection($this->form->get('delegate'), false) ?>
                    </div>
                </div>
            </div>
            <?=$this->formHidden($this->form->get('security'))?>
            <?=$this->formSubmit($this->form->get('update'))?>
        </form>
    </div>
</div>