<?= $this->doctype() ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/card.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
    ?>
    <style>
        body {
            padding-bottom: 20px;
            background-color: rgb(78, 161, 206);
        }
    </style>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
</head>
<body>

<div class="container">
    <?php foreach(['info' => 'alert-info', 'error' => 'alert-danger', 'success' => 'alert-success', 'default' => 'alert-link', 'warning' => 'alert-warning'] as $namespace => $class):?>
        <?= $this->flashMessenger()->renderCurrent($namespace, ['alert', $class]) ?>
        <?= $this->flashMessenger()->render($namespace, ['alert', $class]) ?>
    <?php endforeach?>
    <?= $this->content ?>
</div>
<?= $this->inlineScript() ?>
</body>
</html>