<div class="row">
    <div class="col-md-12">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Discounts</div>
            </div>
            <div class="card-body ">
                <?php if (count($this->discounts) === 0): ?>
                    You haven't created any discounts yet.
                <?php else:?>
                <table class="table table-hover table-in-card">
                    <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Discount</th>
                        <th scope="col">Codes</th>
                        <th scope="col">Available from</th>
                        <th scope="col">Until</th>
                        <th scope="col">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->discounts as $id => $discount):
                            /** @var \ConferenceTools\Attendance\Domain\Discounting\ReadModel\DiscountType $discount */
                            ?>
                            <tr>
                                <td><?= $discount->getName() ?></td>
                                <td><?=$discount->getDiscount() ?></td>
                                <td><?= implode(', ', $discount->getCodes())?></td>
                                <td></td>
                                <td></td>
                                <td>
                                    <a class="btn btn-primary" href="<?=$this->url('attendance-admin/discounts/add-code', ['discountId' => $discount->getId()])?>">
                                        Add new code
                                    </a>
                                </td>
                            </tr>
                        <?php
                        endforeach;
                    endif;
                    ?>
                </table>
            </div>
    </div>
</div>