<div class="row">
    <div class="col-md-12">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Sponsors</div>
            </div>
            <div class="card-body ">
                <?php if (count($this->sponsors) === 0):?>
                    You haven't created any sponsors yet.
                <?php else:?>
                    <table class="table table-hover table-in-card">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->sponsors as $id => $sponsor):
                        /** @var \ConferenceTools\Attendance\Domain\Sponsor\ReadModel\Sponsor $sponsor */
                        ?>
                        <tr>
                            <td><?=$this->escapeHtml($sponsor->getName())?></td>
                            <td>
                                <?php if ($sponsor->getDelegateListId() !== null):?>
                                <a href="<?=$this->url('attendance-admin/sponsors/set-list-last-collection-time', ['sponsorId' => $sponsor->getId()])?>" class="btn btn-primary">Set list last collection time</a>
                                <a href="<?=$this->url('attendance-admin/sponsors/set-list-available-time', ['sponsorId' => $sponsor->getId()])?>" class="btn btn-primary">Set list available time</a>
                                <?php endif?>
                            </td>
                        </tr>
                        <?php endforeach;?>
                        </tbody>
                    </table>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>