<div class="row">
    <div class="col-md-12">
        <div class="card spur-card">
            <div class="card-header">
                <div class="spur-card-icon">
                    <i class="fas fa-table"></i>
                </div>
                <div class="spur-card-title">Sponsors</div>
            </div>
            <div class="card-body ">
                <?php if (count($this->sponsors) === 0):?>
                    You haven't created any sponsors yet.
                <?php else:?>
                    <table class="table table-hover table-in-card">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->sponsors as $id => $sponsor):
                        /** @var \ConferenceTools\Attendance\Domain\Sponsor\ReadModel\Sponsor $sponsor */
                        ?>
                        <tr>
                            <td><?=$this->escapeHtml($sponsor->getName())?></td>
                        </tr>
                        <?php endforeach;?>
                        </tbody>
                    </table>
                <?php endif;?>
            </div>
        </div>
    </div>
</div>